redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\Данил\\Desktop\\Боты\\автопост тест 2710\\TaxiSite\\Сайт Такси1\\frontend\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]